apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: db-creds
      type: Opaque
      data:
        - objectName: 'mongoDb'
          key: 'MONGO_DB'
        - objectName: 'secretJwt'
          key: 'SECRET_JWT '
        - objectName: 'region'
          key: AWS_REGION 
        - objectName: 'cfdKeyId'
          key: AWS_CFD_KEY_ID
        - objectName: 'cfdPrivateKey'
          key: AWS_CFD_PRIVATE_KEY 
        - objectName: 'cfdDomain'
          key: AWS_CFD_DOMAIN 
        - objectName: 'accessKeyId'
          key: AWS_ACCESS_KEY_ID 
        - objectName: 'secretAccessKey'
          key: AWS_SECRET_ACCESS_KEY 
        - objectName: 'bucketName'
          key: AWS_BUCKET_NAME 
  parameters:
    objects: |
      - objectName: 'prod/wallApp/express'
        objectType: 'secretsmanager'
        jmesPath:
          - path: 'MONGO_DB'
            objectAlias: 'mongoDb'
          - path: 'SECRET_JWT'
            objectAlias: 'secretJwt'
          - path: 'AWS_REGION'
            objectAlias: 'region'
          - path: 'AWS_CFD_KEY_ID'
            objectAlias: 'cfdKeyId'
          - path: 'AWS_CFD_PRIVATE_KEY'
            objectAlias: 'cfdPrivateKey'
          - path: 'AWS_CFD_DOMAIN'
            objectAlias: 'cfdDomain'
          - path: 'AWS_ACCESS_KEY_ID'
            objectAlias: 'accessKeyId'
          - path: 'AWS_SECRET_ACCESS_KEY'
            objectAlias: 'secretAccessKey'
          - path: 'AWS_BUCKET_NAME'
            objectAlias: 'bucketName'
          



